package FilterApp;


/**
* FilterApp/Filter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Eclipse/Eclipse-workspace/TrabajoFinalSistemasDistribuidos/src/FilterApp.idl
* sábado 15 de mayo de 2021 13H02' CEST
*/

public interface Filter extends FilterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Filter
