package FilterApp;


/**
* FilterApp/FilterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Eclipse/Eclipse-workspace/TrabajoFinalSistemasDistribuidos/src/FilterApp.idl
* sábado 15 de mayo de 2021 13H02' CEST
*/

public interface FilterOperations 
{
  String getFilterImage (int filter);
  void shutdown ();
} // interface FilterOperations
